-
  name: install python3
  hosts: all
  become: yes
  tasks:
    -
      name: update all
      yum:
        name: '*'
        state: latest
-
  name: copy file from localhost to all dest 
  hosts: all
  tasks:
    -
     name: makr directory
     command: mkdir Ansible creates=Ansible

    -
     name: copy module
     copy:
       src: /home/ec2-user/Ansible/inventory.ini
       dest: ~/Ansible/inventory.ini
